[package]
name = "lb-integrations"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
encoding_rs.workspace = true
lb-platform.workspace = true
md-5.workspace = true
sha2.workspace = true
thiserror.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]
tempfile.workspace = true
