use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::path::PathBuf;
use thiserror::Error;

/// Fields shared by LaunchBox platforms, platform categories, and playlists.
///
/// LaunchBox serializes all of these fields even when many are empty. Optional
/// strings keep the distinction useful to the application without inventing
/// placeholder values.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct NavigationMetadata {
    pub name: String,
    pub nested_name: Option<String>,
    pub sort_title: Option<String>,
    pub notes: Option<String>,
    pub folder: Option<String>,
    pub category: Option<String>,
    pub image_type: Option<String>,
    pub scrape_as: Option<String>,
    pub hide_in_big_box: bool,
    pub local_db_parsed: bool,
    pub last_game_id: Option<String>,
    pub last_selected_child: Option<String>,
    pub cpu: Option<String>,
    pub developer: Option<String>,
    pub display: Option<String>,
    pub graphics: Option<String>,
    pub manufacturer: Option<String>,
    pub max_controllers: Option<String>,
    pub media: Option<String>,
    pub memory: Option<String>,
    pub sound: Option<String>,
    pub android_theme_video_path: Option<String>,
    pub back_images_folder: Option<String>,
    pub banner_images_folder: Option<String>,
    pub big_box_theme: Option<String>,
    pub big_box_view: Option<String>,
    pub clear_logo_images_folder: Option<String>,
    pub fanart_images_folder: Option<String>,
    pub front_images_folder: Option<String>,
    pub manuals_folder: Option<String>,
    pub music_folder: Option<String>,
    pub screenshot_images_folder: Option<String>,
    pub steam_banner_images_folder: Option<String>,
    pub video_path: Option<String>,
    pub videos_folder: Option<String>,
}

impl NavigationMetadata {
    pub fn validate(&self, record: &'static str) -> Result<(), CatalogValidationError> {
        if self.name.trim().is_empty() {
            return Err(CatalogValidationError::MissingName { record });
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct PlatformDefinition {
    pub metadata: NavigationMetadata,
    pub release_date: Option<String>,
    pub disable_auto_import: bool,
}

impl PlatformDefinition {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        self.metadata.validate("Platform")
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct PlatformCategory {
    pub metadata: NavigationMetadata,
    pub is_autogenerated: bool,
    pub disable_auto_import: bool,
}

impl PlatformCategory {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        self.metadata.validate("PlatformCategory")
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct PlatformFolder {
    pub platform: String,
    pub media_type: String,
    pub folder_path: String,
}

impl PlatformFolder {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        require_field("PlatformFolder", "Platform", &self.platform)?;
        require_field("PlatformFolder", "MediaType", &self.media_type)?;
        require_field("PlatformFolder", "FolderPath", &self.folder_path)
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct PlatformCatalog {
    pub source_path: PathBuf,
    pub platforms: Vec<PlatformDefinition>,
    pub categories: Vec<PlatformCategory>,
    pub folders: Vec<PlatformFolder>,
}

impl PlatformCatalog {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        let mut platform_names = BTreeSet::new();
        for platform in &self.platforms {
            platform.validate()?;
            let name = platform.metadata.name.to_lowercase();
            if !platform_names.insert(name) {
                return Err(CatalogValidationError::DuplicateName {
                    record: "Platform",
                    name: platform.metadata.name.clone(),
                });
            }
        }
        let mut category_names = BTreeSet::new();
        for category in &self.categories {
            category.validate()?;
            let name = category.metadata.name.to_lowercase();
            if !category_names.insert(name) {
                return Err(CatalogValidationError::DuplicateName {
                    record: "PlatformCategory",
                    name: category.metadata.name.clone(),
                });
            }
        }
        for folder in &self.folders {
            folder.validate()?;
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct Playlist {
    pub id: String,
    pub metadata: NavigationMetadata,
    pub auto_populate: bool,
    pub include_with_platforms: bool,
    pub is_autogenerated: bool,
    pub sort_by: Option<String>,
}

impl Playlist {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        require_field("Playlist", "PlaylistId", &self.id)?;
        self.metadata.validate("Playlist")
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct PlaylistFilter {
    pub field_key: String,
    pub comparison_type_key: String,
    pub value: String,
}

impl PlaylistFilter {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        require_field("PlaylistFilter", "FieldKey", &self.field_key)?;
        require_field(
            "PlaylistFilter",
            "ComparisonTypeKey",
            &self.comparison_type_key,
        )
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct PlaylistGame {
    pub game_id: String,
    pub game_title: String,
    pub game_platform: String,
    pub game_file_name: String,
    pub launchbox_db_id: Option<u64>,
    pub manual_order: i64,
}

impl PlaylistGame {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        require_field("PlaylistGame", "GameId", &self.game_id)?;
        require_field("PlaylistGame", "GameTitle", &self.game_title)?;
        require_field("PlaylistGame", "GamePlatform", &self.game_platform)
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct PlaylistDocument {
    pub source_path: PathBuf,
    pub playlist: Playlist,
    pub filters: Vec<PlaylistFilter>,
    pub games: Vec<PlaylistGame>,
}

impl PlaylistDocument {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        self.playlist.validate()?;
        for filter in &self.filters {
            filter.validate()?;
        }
        for game in &self.games {
            game.validate()?;
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct Emulator {
    pub id: String,
    pub title: String,
    pub application_path: String,
    pub command_line: Option<String>,
    pub default_platform: Option<String>,
    pub auto_extract: bool,
    pub aggressive_window_hiding: bool,
    pub default_pause_settings_pushed: bool,
    pub disable_shutdown_screen: bool,
    pub enable_hardcore_achievements: bool,
    pub file_name_without_extension_and_path: bool,
    pub forceful_pause_screen_activation: bool,
    pub hide_all_non_exclusive_fullscreen_windows: bool,
    pub hide_console: bool,
    pub hide_mouse_cursor_in_game: bool,
    pub login_to_cheevo_on_game_launch: bool,
    pub no_quotes: bool,
    pub no_space: bool,
    pub skip_version_check: bool,
    pub startup_load_delay: u64,
    pub suspend_process_on_pause: bool,
    pub use_pause_screen: bool,
    pub use_startup_screen: bool,
    pub auto_hotkey_script: Option<String>,
    pub exit_auto_hotkey_script: Option<String>,
    pub load_state_auto_hotkey_script: Option<String>,
    pub pause_auto_hotkey_script: Option<String>,
    pub reset_auto_hotkey_script: Option<String>,
    pub resume_auto_hotkey_script: Option<String>,
    pub save_state_auto_hotkey_script: Option<String>,
    pub swap_discs_auto_hotkey_script: Option<String>,
}

impl Emulator {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        require_field("Emulator", "ID", &self.id)?;
        require_field("Emulator", "Title", &self.title)
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct EmulatorPlatform {
    pub emulator_id: String,
    pub platform: String,
    pub command_line: Option<String>,
    pub default: bool,
    /// `None` means the platform inherits the emulator-level extraction rule.
    pub auto_extract: Option<bool>,
    pub m3u_disc_load_enabled: bool,
}

impl EmulatorPlatform {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        require_field("EmulatorPlatform", "Emulator", &self.emulator_id)?;
        require_field("EmulatorPlatform", "Platform", &self.platform)
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct EmulatorConfiguration {
    pub source_path: PathBuf,
    pub emulators: Vec<Emulator>,
    pub platforms: Vec<EmulatorPlatform>,
}

impl EmulatorConfiguration {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        for emulator in &self.emulators {
            emulator.validate()?;
        }
        for platform in &self.platforms {
            platform.validate()?;
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct ParentRelationship {
    pub parent_platform_category_name: Option<String>,
    pub parent_platform_name: Option<String>,
    pub parent_playlist_id: Option<String>,
    pub platform_category_name: Option<String>,
    pub platform_name: Option<String>,
    pub playlist_id: Option<String>,
}

impl ParentRelationship {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        let children = [
            self.platform_category_name.as_deref(),
            self.platform_name.as_deref(),
            self.playlist_id.as_deref(),
        ]
        .into_iter()
        .flatten()
        .filter(|value| !value.trim().is_empty())
        .count();
        if children != 1 {
            return Err(CatalogValidationError::InvalidParentChildCount { actual: children });
        }

        let parents = [
            self.parent_platform_category_name.as_deref(),
            self.parent_platform_name.as_deref(),
            self.parent_playlist_id.as_deref(),
        ]
        .into_iter()
        .flatten()
        .filter(|value| !value.trim().is_empty())
        .count();
        if parents > 1 {
            return Err(CatalogValidationError::InvalidParentTargetCount { actual: parents });
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct GameController {
    pub id: String,
    pub name: String,
    pub category: String,
    pub associated_platforms: Option<String>,
}

impl GameController {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        require_field("GameController", "Id", &self.id)?;
        require_field("GameController", "Name", &self.name)
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct InputBinding {
    pub input_action: String,
    pub controller_binding: String,
    pub controller_hold_binding: String,
}

impl InputBinding {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        require_field("InputBinding", "InputAction", &self.input_action)
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct ListCacheItem {
    pub playlist_id: String,
    pub launchbox_count: u64,
    pub launchbox_include_broken: bool,
    pub launchbox_include_hidden: bool,
    pub launchbox_exclude_games_missing_background_image: bool,
    pub launchbox_exclude_games_missing_box_front_image: bool,
    pub launchbox_exclude_games_missing_clear_logo_image: bool,
    pub launchbox_exclude_games_missing_screenshot_image: bool,
    pub launchbox_exclude_games_missing_videos: bool,
    pub big_box_count: u64,
    pub big_box_include_broken: bool,
    pub big_box_include_hidden: bool,
    pub big_box_exclude_games_missing_background_image: bool,
    pub big_box_exclude_games_missing_box_front_image: bool,
    pub big_box_exclude_games_missing_clear_logo_image: bool,
    pub big_box_exclude_games_missing_screenshot_image: bool,
    pub big_box_exclude_games_missing_videos: bool,
}

impl ListCacheItem {
    pub fn validate(&self) -> Result<(), CatalogValidationError> {
        require_field("ListCacheItem", "PlaylistId", &self.playlist_id)
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct SettingEntry {
    pub key: String,
    /// Exact scalar text, including an empty string when LaunchBox wrote an
    /// empty element. Callers choose the type appropriate for each key.
    pub value: String,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct ImageTypeSetting {
    pub image_type: String,
    pub is_default: bool,
    pub use_in_auto_imports: bool,
}

#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct FrontendSettings {
    pub source_path: PathBuf,
    pub record_name: String,
    pub entries: Vec<SettingEntry>,
    pub image_type_settings: Vec<ImageTypeSetting>,
}

impl FrontendSettings {
    pub fn get(&self, key: &str) -> Option<&str> {
        self.entries
            .iter()
            .find(|entry| entry.key == key)
            .map(|entry| entry.value.as_str())
    }

    pub fn get_bool(&self, key: &str) -> Option<bool> {
        match self.get(key)? {
            value if value.eq_ignore_ascii_case("true") => Some(true),
            value if value.eq_ignore_ascii_case("false") => Some(false),
            _ => None,
        }
    }

    pub fn get_i64(&self, key: &str) -> Option<i64> {
        self.get(key)?.parse().ok()
    }
}

fn require_field(
    record: &'static str,
    field: &'static str,
    value: &str,
) -> Result<(), CatalogValidationError> {
    if value.trim().is_empty() {
        Err(CatalogValidationError::MissingField { record, field })
    } else {
        Ok(())
    }
}

#[derive(Clone, Debug, Error, Eq, PartialEq)]
pub enum CatalogValidationError {
    #[error("{record} is missing its name")]
    MissingName { record: &'static str },
    #[error("{record} is missing required {field}")]
    MissingField {
        record: &'static str,
        field: &'static str,
    },
    #[error("{record} name occurs more than once: {name}")]
    DuplicateName { record: &'static str, name: String },
    #[error("Parent must identify exactly one child, found {actual}")]
    InvalidParentChildCount { actual: usize },
    #[error("Parent identifies more than one parent target, found {actual}")]
    InvalidParentTargetCount { actual: usize },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parent_relationship_requires_one_child_and_at_most_one_parent() {
        let valid = ParentRelationship {
            parent_platform_category_name: Some("Consoles".into()),
            platform_name: Some("Fixture Console".into()),
            ..ParentRelationship::default()
        };
        assert_eq!(valid.validate(), Ok(()));

        let missing_child = ParentRelationship::default();
        assert_eq!(
            missing_child.validate(),
            Err(CatalogValidationError::InvalidParentChildCount { actual: 0 })
        );

        let ambiguous_parent = ParentRelationship {
            parent_platform_category_name: Some("Consoles".into()),
            parent_platform_name: Some("Arcade".into()),
            platform_name: Some("Fixture Console".into()),
            ..ParentRelationship::default()
        };
        assert_eq!(
            ambiguous_parent.validate(),
            Err(CatalogValidationError::InvalidParentTargetCount { actual: 2 })
        );
    }

    #[test]
    fn platform_catalog_rejects_case_insensitive_duplicate_names() {
        let mut catalog = PlatformCatalog::default();
        catalog.platforms.push(PlatformDefinition {
            metadata: NavigationMetadata {
                name: "Arcade".into(),
                ..NavigationMetadata::default()
            },
            ..PlatformDefinition::default()
        });
        catalog.platforms.push(PlatformDefinition {
            metadata: NavigationMetadata {
                name: "arcade".into(),
                ..NavigationMetadata::default()
            },
            ..PlatformDefinition::default()
        });
        assert_eq!(
            catalog.validate(),
            Err(CatalogValidationError::DuplicateName {
                record: "Platform",
                name: "arcade".into(),
            })
        );
    }

    #[test]
    fn platform_catalog_rejects_case_insensitive_duplicate_category_names() {
        let mut catalog = PlatformCatalog::default();
        catalog.categories.push(PlatformCategory {
            metadata: NavigationMetadata {
                name: "Collections".into(),
                ..NavigationMetadata::default()
            },
            ..PlatformCategory::default()
        });
        catalog.categories.push(PlatformCategory {
            metadata: NavigationMetadata {
                name: "collections".into(),
                ..NavigationMetadata::default()
            },
            ..PlatformCategory::default()
        });
        assert_eq!(
            catalog.validate(),
            Err(CatalogValidationError::DuplicateName {
                record: "PlatformCategory",
                name: "collections".into(),
            })
        );
    }

    #[test]
    fn parent_relationship_accepts_a_playlist_parent() {
        let relationship = ParentRelationship {
            parent_playlist_id: Some("favorites".into()),
            platform_category_name: Some("Handhelds".into()),
            ..ParentRelationship::default()
        };
        assert_eq!(relationship.validate(), Ok(()));
    }

    #[test]
    fn settings_accessors_do_not_guess_invalid_types() {
        let settings = FrontendSettings {
            entries: vec![
                SettingEntry {
                    key: "Enabled".into(),
                    value: "True".into(),
                },
                SettingEntry {
                    key: "Count".into(),
                    value: "12".into(),
                },
                SettingEntry {
                    key: "Theme".into(),
                    value: "Default".into(),
                },
            ],
            ..FrontendSettings::default()
        };
        assert_eq!(settings.get_bool("Enabled"), Some(true));
        assert_eq!(settings.get_i64("Count"), Some(12));
        assert_eq!(settings.get_bool("Theme"), None);
    }
}
